# Generated by Django 3.2.4 on 2021-06-26 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_model', models.CharField(max_length=200)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Claim.users')),
            ],
        ),
        migrations.CreateModel(
            name='Losses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(verbose_name='datetime of accident')),
                ('location', models.CharField(max_length=254)),
                ('loss_type', models.IntegerField(choices=[(1, 'Own Damage'), (2, 'Knock of Knock'), (3, 'Windscreen Damage'), (4, 'Theft')])),
                ('description', models.TextField()),
                ('police_report_lodge', models.BooleanField()),
                ('injured_status', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Claim.users')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='tmp')),
                ('pdf', models.FileField(upload_to='pdf')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Claim.users')),
            ],
        ),
    ]
