# Generated by Django 3.2.4 on 2021-06-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Claim', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
        migrations.RenameModel(
            old_name='Losses',
            new_name='Loss',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameModel(
            old_name='Vehicles',
            new_name='Vehicle',
        ),
    ]
