# Generated by Django 3.2.4 on 2021-06-26 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Claim', '0002_auto_20210626_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in progress', 'In Progress'), ('accepted', 'Accepted')], max_length=200)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Claim.document')),
                ('loss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Claim.loss')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Claim.user')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Claim.vehicle')),
            ],
        ),
    ]
