# Generated by Django 3.2.4 on 2021-06-27 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Claim', '0005_auto_20210626_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='loss',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='user_id',
        ),
    ]
